feat: improve linting (#164)

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -24,7 +24,7 @@ jobs:
   lint:
     working_directory: ~/repo
     docker:
-      - image: alpine/helm:3.5.2
+      - image: alpine/helm:3.12.1
     steps:
       - run:
           <<: *defaults_Dependencies
@@ -37,6 +37,62 @@ jobs:
       - run:
           name: Linting Helm Charts
           command: ./scripts/lint-charts.sh
+      - run:
+          name: Rendering Helm Charts
+          command: |
+            curl -L --output /usr/bin/yq https://github.com/mikefarah/yq/releases/download/v4.45.1/yq_linux_amd64
+            chmod +x /usr/bin/yq
+            yq --version
+            bash ./scripts/lint-render.sh
+      - persist_to_workspace:
+          root: .
+          paths:
+            - test
+            - package.json
+            - package-lock.json
+            - eslint.config.mjs
+
+  test-lint-yaml:
+    machine:
+      image: ubuntu-2004:current
+    steps:
+      - attach_workspace:
+          at: .
+      - run:
+          name: Set up nvm
+          command: |
+            # Note: this needs to be separate from the nvm install step
+            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
+            echo "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV
+      - run:
+          name: Install and run linter
+          command: |
+            nvm install v20.18.0 && nvm alias default v20.18.0
+            node --version
+            npm ci --legacy-peer-deps
+            npm run lint || { echo -e "\e[31mLinting failed, check the report in artifacts\e[0m"; exit 1; }
+      - store_artifacts:
+          path: /home/circleci/project/test/lint.html
+          destination: Lint-YAML
+  test-lint-k8s:
+    machine:
+      image: ubuntu-2004:current
+    steps:
+      - attach_workspace:
+          at: .
+      - run:
+          name: Download kubectl-validate
+          command: |
+            curl -L --output ./kubectl-validate https://github.com/kubernetes-sigs/kubectl-validate/releases/download/v0.0.4/kubectl-validate_linux_amd64.tar.gz
+            tar -xvf ./kubectl-validate
+            chmod +x ./kubectl-validate
+      - run:
+          name: Run kubectl-validate
+          command: |
+            ./kubectl-validate test --version 1.32 |& grep -v $'OK\033\[0m$' | sed '/^$/N;/^\n$/D'
+      - store_artifacts:
+          path: /home/circleci/project/test
+          destination: Lint-k8s
 
   build_and_publish_chart:
     working_directory: ~/repo
@@ -84,9 +140,31 @@ workflows:
             branches:
               ignore:
                 - gh-pages
+      - test-lint-yaml:
+          context: org-global
+          requires:
+            - lint
+          filters:
+            tags:
+              only: /.*/
+            branches:
+              ignore:
+                - gh-pages
+      - test-lint-k8s:
+          context: org-global
+          requires:
+            - lint
+          filters:
+            tags:
+              only: /.*/
+            branches:
+              ignore:
+                - gh-pages
       - build_and_publish_chart:
           requires:
             - lint
+            - test-lint-yaml
+            - test-lint-k8s
           filters:
             tags:
               only: /^v.*/
