Testing the master chart is out of scope

diff --git a/.github/workflows/validate-chart.yml b/.github/workflows/validate-chart.yml
--- a/.github/workflows/validate-chart.yml
+++ b/.github/workflows/validate-chart.yml
@@ -103,42 +103,42 @@ jobs:
       run: time helm install --wait --wait-for-jobs int-test ./mojaloop-simulator-backend/
 
 
-  smoke_test_deploy_payment_manager:
-    timeout-minutes: 15
-    needs:
-    - validate_payment_manager_manifests
-    - smoke_test_deploy_sim_backend
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v2
-
-    - uses: cachix/install-nix-action@v13
-      with:
-        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/8e4fe32876ca15e3d5eb3ecd3ca0b224417f5f17.tar.gz
-
-    - name: Install dependencies
-      run: nix-env -if ci-helpers/default.nix
-
-    - name: Start cluster
-      run: |-
-        k3d cluster create \
-          --kubeconfig-update-default \
-          --kubeconfig-switch-context \
-          --image=rancher/k3s:v1.17.9-k3s1 \
-          int-test
-
-    - name: Deploy
-      run: |-
-        time \
-          helm install \
-            --dependency-update \
-            --wait \
-            --wait-for-jobs \
-            -f environments/values-minikube.yaml \
-            int-test \
-            ./mojaloop-payment-manager
-
-    # Enable tmate debugging of failed, or manually-triggered workflows if the input option was provided
-    - name: Setup tmate session
-      uses: mxschmitt/action-tmate@v3
-      if: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled) || failure() }}
+  # smoke_test_deploy_payment_manager:
+  #   timeout-minutes: 15
+  #   needs:
+  #   - validate_payment_manager_manifests
+  #   - smoke_test_deploy_sim_backend
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #   - uses: actions/checkout@v2
+  #
+  #   - uses: cachix/install-nix-action@v13
+  #     with:
+  #       nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/8e4fe32876ca15e3d5eb3ecd3ca0b224417f5f17.tar.gz
+  #
+  #   - name: Install dependencies
+  #     run: nix-env -if ci-helpers/default.nix
+  #
+  #   - name: Start cluster
+  #     run: |-
+  #       k3d cluster create \
+  #         --kubeconfig-update-default \
+  #         --kubeconfig-switch-context \
+  #         --image=rancher/k3s:v1.17.9-k3s1 \
+  #         int-test
+  #
+  #   - name: Deploy
+  #     run: |-
+  #       time \
+  #         helm install \
+  #           --dependency-update \
+  #           --wait \
+  #           --wait-for-jobs \
+  #           -f environments/values-minikube.yaml \
+  #           int-test \
+  #           ./mojaloop-payment-manager
+  #
+  #   # Enable tmate debugging of failed, or manually-triggered workflows if the input option was provided
+  #   - name: Setup tmate session
+  #     uses: mxschmitt/action-tmate@v3
+  #     if: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled) || failure() }}
